import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../../../../core/api/api_client.dart';
import '../../../../core/api/api_endpoints.dart';
import '../../../../core/popups/feros_snackbar.dart';
import '../../../../core/services/auth_service.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/theme/app_text_styles.dart';
import '../../../../core/widgets/feros_pin_input.dart';

class ForcePinChangeView extends StatefulWidget {
  const ForcePinChangeView({super.key});

  @override
  State<ForcePinChangeView> createState() => _ForcePinChangeViewState();
}

class _ForcePinChangeViewState extends State<ForcePinChangeView> {
  final _api  = Get.find<ApiClient>();
  final _auth = Get.find<AuthService>();

  String _currentPin = '';
  String _newPin     = '';
  String _confirmPin = '';
  bool   _loading    = false;

  bool get _canSubmit =>
      _currentPin.length == 4 &&
      _newPin.length == 4 &&
      _confirmPin.length == 4;

  Future<void> _submit() async {
    if (_newPin != _confirmPin) {
      FerosSnackbar.error('New PIN and confirm PIN do not match');
      return;
    }
    setState(() => _loading = true);
    try {
      await _api.patch(ApiEndpoints.changePin, data: {
        'currentPin': _currentPin,
        'newPin':     _newPin,
      });
      FerosSnackbar.success('PIN changed successfully. Please login with your new PIN.');
      await _auth.logout();
    } catch (_) {
      FerosSnackbar.error('Failed to change PIN. Check your current PIN.');
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return PopScope(
      canPop: false,
      child: Scaffold(
        backgroundColor: AppColors.background,
        body: SafeArea(
          child: ListView(
            padding: const EdgeInsets.all(24),
            children: [
              const SizedBox(height: 16),

              // ── Info banner ───────────────────────────────────
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: const Color(0xFFEFF6FF),
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: AppColors.navy.withValues(alpha: 0.15)),
                ),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Icon(Icons.lock_reset_outlined,
                        color: AppColors.navy, size: 22),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'PIN Change Required',
                            style: AppTextStyles.bodySemiBold
                                .copyWith(color: AppColors.navy),
                          ),
                          const SizedBox(height: 4),
                          Text(
                            'Your PIN was reset by an admin. Please set a new PIN to continue using the app.',
                            style: AppTextStyles.caption
                                .copyWith(color: AppColors.navy.withValues(alpha: 0.75)),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 28),

              // ── PIN form ──────────────────────────────────────
              Container(
                padding: const EdgeInsets.all(20),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(12),
                  boxShadow: const [
                    BoxShadow(
                        color: Color(0x0A000000),
                        blurRadius: 8,
                        offset: Offset(0, 2)),
                  ],
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _PinField(
                      label: 'Current PIN (generated by admin)',
                      onChanged: (v) => setState(() => _currentPin = v),
                    ),
                    const SizedBox(height: 24),
                    _PinField(
                      label: 'New PIN',
                      onChanged: (v) => setState(() => _newPin = v),
                    ),
                    const SizedBox(height: 24),
                    _PinField(
                      label: 'Confirm New PIN',
                      onChanged: (v) => setState(() => _confirmPin = v),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 28),

              // ── Submit button ─────────────────────────────────
              SizedBox(
                width: double.infinity,
                child: ElevatedButton(
                  onPressed: (_canSubmit && !_loading) ? _submit : null,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AppColors.navy,
                    foregroundColor: Colors.white,
                    disabledBackgroundColor:
                        AppColors.navy.withValues(alpha: 0.4),
                    elevation: 0,
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(10)),
                  ),
                  child: _loading
                      ? const SizedBox(
                          width: 20,
                          height: 20,
                          child: CircularProgressIndicator(
                              strokeWidth: 2, color: Colors.white),
                        )
                      : Text(
                          'Set New PIN',
                          style: AppTextStyles.bodyMedium.copyWith(
                              color: Colors.white,
                              fontWeight: FontWeight.w600),
                        ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _PinField extends StatelessWidget {
  final String label;
  final ValueChanged<String> onChanged;
  const _PinField({required this.label, required this.onChanged});

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(label,
            style: AppTextStyles.label.copyWith(color: AppColors.navy)),
        const SizedBox(height: 10),
        FerosPinInput(onCompleted: onChanged),
      ],
    );
  }
}
